import { Comment } from './../../models/issue.model';
import { Component } from '@angular/core';
import { IssueService } from '../../services/issue.service';
import { ActivatedRoute, Router } from '@angular/router';

import { CommentService } from '../../services/comment.service';
@Component({
  selector: 'app-add-comment',
  templateUrl: './add-comment.component.html',
  styleUrl: './add-comment.component.css'
})
export class AddCommentComponent {
  issueId: number | null = null;
  comment: Comment = {
    id: 0,  // id will be auto-generated by the backend
    text: '',
    issueId: 0
  };

  constructor(private commentService:CommentService,private issueService: IssueService, private route: ActivatedRoute, private router: Router) {
    this.route.paramMap.subscribe(params => {
      this.issueId = +params.get('issueId')!;


      this.comment.issueId = this.issueId;
    
    });
  }

  saveComment(): void {
    console.log(this.comment.issueId)
    this.commentService.addComment(this.comment).subscribe(() => {
      // Navigate back to the comments list after saving the new comment
      this.router.navigate(['/comments', this.issueId]);
    });
  }
}
