import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { IssueService } from '../../services/issue.service';
import { Issue } from '../../models/issue.model';

@Component({
  selector: 'app-add-issue',
  templateUrl: './add-issue.component.html',
  styleUrls: ['./add-issue.component.css']
})
export class AddIssueComponent {
  issue: Issue = {
    id: 0,  // id will be auto-generated by the backend
    title: '',
    description: '',
    resolved: false,
    comments: []  // Initialize comments as an empty array
  };
  isEditMode = false;
  constructor(private issueService: IssueService, private router: Router,private route: ActivatedRoute) { }


  ngOnInit(): void {
    this.route.paramMap.subscribe(params => {
      const id = params.get('id');
      if (id) {
        this.isEditMode = true;
        this.issueService.getIssueById(+id).subscribe(issue => {
          this.issue = issue;
        });
      }
    });
  }

  saveIssue(): void {
    if (this.isEditMode) {
      this.issueService.updateIssue(this.issue.id, this.issue).subscribe(() => {
        this.router.navigate(['issues']);
      });
    } else {
      this.issueService.createIssue(this.issue).subscribe(() => {
        this.router.navigate(['issues']);
      });
    }
  }
}
